### ISSUE TITLE
Error compiling Less stylesheet

### ISSUE THREAD

**Issue by amichuda** [BenRussert/data-explorer#8]
Hi,

When installing the data-explorer, I get this error:

`
Line number: 3
'../node_modules/@blueprintjs/icons/lib/css/blueprint-icons.css' wasn't found. Tried - /home/lordflaron/.atom/packages/data-explorer/node_modules/@blueprintjs/icons/lib/css/blueprint-icons.css,/usr/lib/atom/node_modules/one-light-syntax/node_modules/@blueprintjs/icons/lib/css/blueprint-icons.css,/usr/lib/atom/node_modules/one-light-ui/node_modules/@blueprintjs/icons/lib/css/blueprint-icons.css,/usr/lib/atom/static/node_modules/@blueprintjs/icons/lib/css/blueprint-icons.css,/usr/lib/atom/node_modules/@blueprintjs/icons/lib/css/blueprint-icons.css,../node_modules/@blueprintjs/icons/lib/css/blueprint-icons.css
`

Is there a missing dependency I need?

Thank you so much!

**Comment by matgad** [comment]
Hi,
same problem here.

**Comment by matgad** [comment]
I just checked and since Mar 22, 2019 blueprintjs is no longer a dependency of @nteract/data-explorer.

**Comment by BenRussert** [comment]
@matgad you have the issue explained there. If you want to make a PR bumping the version and removing the blueprint stylesheet stylesheet imports id ship the patch release when I get home tonight.

**Comment by BenRussert** [comment]
This is fixed on the `v0.6.0` release. Thanks all for the report!
